<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
            schematypens="http://www.w3.org/2001/XMLSchema"?>

<package format="3">
  <name>parkdoyeon_day3_hw1</name>
  <version>0.0.0</version>

  <description>ROS2 Day1 Homework 3 - Turtlesim Shape Drawer</description>

  <maintainer email="doyeon@example.com">
    doyeon
  </maintainer>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

<depend>rclcpp</depend>
<depend>geometry_msgs</depend>
<depend>turtlesim</depend>
<depend>std_srvs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>